runtime: python39
service: dillmoe
handlers:
  # Serve specific HTML files
  - url: /(call|nzp|director)
    static_files: \1.html
    upload: (call|nzp|director)\.html

  # Serve index.html for the root path and subdirectories
  - url: /(.*/)?$
    static_files: \1index.html
    upload: (.*)/index\.html

  # Serve all other static files
  - url: /(.*)
    static_files: \1
    upload: (.*)

  # Explicitly serve SVG files
  - url: /assets/svg/(.*\.svg)
    mime_type: image/svg+xml
    static_files: assets/svg/\1
    upload: assets/svg/.*\.svg

# Optional: Configure default expiration for static content
default_expiration: "30d"